version: "3"
services:
  react:
    build: ./frontend/
      # context: .
      # dockerfile: ./frontend/Dockerfile
    container_name: react-app-container
    image: node:16-alpine
    volumes:
      - ./frontend:/app/react
    command: sh -c "cd /app/react && npm install && npm run dev"
    ports:
      - '5173:5173'
  go:
    build:
      context: ./backend/
      # dockerfile: ./backend/Dockerfile
    container_name: go_container
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./backend:/app/go
  db:
    build:
      context: ./db/
    container_name: db_container
    environment:
      MYSQL_DATABASE: tanni-uru
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    ports:
    - 4306:3306
    links:
      - go
  migrate:
    build: ./db/migrations
    container_name: migrate_container
    depends_on:
      - db
    command: ['up']
    environment:
      WAIT_HOSTS: db:3306
      MIGRATIONS_DIR: /migrations
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: tanni-uru
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./db/migrations/migrations:/migrations