services:
  react:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: react-app-container
    image: node:16-alpine
    volumes:
      - ./frontend:/app/react
    command: sh -c "cd /app/react && npm install && npm run dev"
    ports:
      - '5173:5173'
  go:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: go_container
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./backend:/app/go
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tanni-uru
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
    links:
      - go