services:
  app:
    container_name: react-app-container
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - '5173:5173'
